### ISSUE TITLE
Does not fail to compile when not specifying arguments that match the format string

### ISSUE THREAD

**Issue by Ten0** [Lucretiel/lazy_format#5]
`lazy_format` does not fail to compile if forgetting to pass the arguments of the format string to the macro:
```rust
let x = lazy_format!("{}");
```
This behavior is inconsistent with `format_args!`, `write!`, `format!` and [with the latest rust edition](https://blog.rust-lang.org/2021/05/11/edition-2021.html#panic-macro-consistency)... and opens the door for mistakes where one forgets to specify the arguments (which is probably the reason why the standard library did not allow this).

If one doesn't need arguments they may typically just use an `&str` and not `format_args!` anyway, so I don't think it's useful as a feature. Also, if anyone actually needs this, they may implement it separately pretty easily.

=> This should clearly at least be an opt-in, if it exists at all.

**Comment by Lucretiel** [comment]
Thanks for the report; fixed in [1.10.0](https://crates.io/crates/lazy_format/1.10.0)
